Fix an issue with `mocha --watch`
When running tests with `mocha --watch` the following exception is thrown:

  TypeError: Cannot redefine property: testing

Here is the fix for it. We should be more careful in the future, since the `watch` param is super useful and a lot of developers are using it.